### ISSUE TITLE
Cannot play any eurosport stream

### ISSUE THREAD

**Issue by crabtre** [JinRonin/plugin.video.eurosportplayer#10]
Eurosport Player has been working fine.  Account is valid and can stream on other devices.  Eurosport player opens fine on Kodi and I can browse the videos available as well as the livestreams, but if I attempt to select any of them I receive an error that it cannot be played and to review the log.  I've attached a debug log and the error seems to be related to the parser.py file, but I am not an experienced developer and am likely wrong.  Any help that you can give would be appreciated.

[Kodi Debug Log.zip](https://github.com/JinRonin/plugin.video.eurosportplayer/files/2171799/Kodi.Debug.Log.zip)

**Comment by usphil** [comment]
I just tried to watch Wimbledon replays but got the same error on both version 2.0.10 and 2.0.11

**Comment by sscraggles** [comment]
Same problem here...
`01:13:05.833 T:140520601409280   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'dict' object has no attribute 'replace'
                                            Traceback (most recent call last):
                                              File "/home/htpc/.kodi/addons/plugin.video.eurosportplayer/addon.py", line 63, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/htpc/.kodi/addons/plugin.video.eurosportplayer/addon.py", line 45, in router
                                                parser.play(client.streams(id_))
                                              File "/home/htpc/.kodi/addons/plugin.video.eurosportplayer/resources/lib/parser.py", line 119, in play
                                                path = data['stream'][i].replace('desktop','wired50')
                                            AttributeError: 'dict' object has no attribute 'replace'
                                            -->End of Python script error report<--
01:13:05.856 T:140524203969408   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.eurosportplayer/?id=https%3A%2F%2Fglobal-api.svcs.eurosportplayer.com%2Fchannels%2F271431e9-9cf9-4413-90e3-5181e1eec928%2Fscenarios%2F%7Bscenario%7D&params=&mode=play&title=E1BR+%5BI%5DTennis%3A+Wimbledon%5B%2FI%5D]`

**Comment by JinRonin** [comment]
Sorry, i won't have time today to look into this.
I will try to fix it tomorrow.

**Comment by prothed** [comment]
Same problem and log message as sscraggles above.
Everything ok yesterday, but nothing working this morning.............

**Comment by JinRonin** [comment]
just pushed an update. please test and report. thanks

here is a clean zip just in case:
https://www.dropbox.com/s/oex1z1sw4fmm741/plugin.video.eurosportplayer-2.0.11.zip?dl=1

**Comment by crabtre** [comment]
I've installed on Kodi 17.6 and its back to working beautifully.  Thank you very much for the fix!

**Comment by prothed** [comment]
Downloaded from dropbox.  Works fine.  Thank you!

**Comment by JinRonin** [comment]
Thanks for the report and feedback. I have opened a pull request for the repo.
Once its added you will receive a further update as another version bump (2.1.0) is inlcuded.
