### ISSUE TITLE
Streams won't start anymore (skipping unplayable item)

### ISSUE THREAD

**Issue by olfolfolf** [JinRonin/plugin.video.eurosportplayer#11]
```
CoreELEC 8.95.1
InputStream Adaptive 2.2.27.0
Eurosport Player 2.20
```

Since a few days, streams in Eurosport Player aren't starting anymore. No problems with DAZN or Netflix.

Debug-Log: http://ix.io/1mpc

Any ideas?

**Comment by JinRonin** [comment]
Set addon settings to standard and relogin. There is either an issue with the auth token or your subscription has ended.

**Comment by olfolfolf** [comment]
Setting the addon to standard did not force a relogin.
I uninstalled / installed the addon, then I had to login and it works again. Thanks!

**Comment by olfolfolf** [comment]
Would it be possible to implement a "delete login" option into the addon settings?

**Comment by JinRonin** [comment]
Resetting the settings should be enough. No idea why it didnt work for you but i will try to work on a solution for this specific issue.

**Comment by olfolfolf** [comment]
> 
> 
> Resetting the settings should be enough. No idea why it didnt work for you but i will try to work on a solution for this specific issue.

Thanks!

**Comment by STPKITT** [comment]
But resetting the settings resets more than just login credentials so I'd vote for a "delete login" option.
