### ISSUE TITLE
There is no sound when changing the audio language

### ISSUE THREAD

**Issue by pallinko** [JinRonin/plugin.video.eurosportplayer#2]
Hello.
Work only audio English. LibreELEC 8.2.3 on Raspberry PI 3 and KODI 17.6 on Android. Win 10 with KODI 18 audio language work. Thank you for your super plugin.
[kodi.log](https://github.com/JinRonin/plugin.video.eurosportplayer/files/1711723/kodi.log)

**Comment by JinRonin** [comment]
Yes, this has been fixed in inputstream adaptive and requires kodi 18.
You will have to update your pi/android kodi version in order to get it to work.

**Comment by pallinko** [comment]
I've  upgraded Raspberry Pi to KODI 18 (LibreELEC) and everything works. Thank you.
