### ISSUE TITLE
Can’t play stream

### ISSUE THREAD

**Issue by 123chuck123** [JinRonin/plugin.video.eurosportplayer#5]
I can’t play any stream anymore. Yesterday I updated my Kodi 18 Build.
Using Kodi on Arch Linux with a Laptop.
Tried to uninstall and reinstall the addon but without any success.
Amazon, DAZN, Maxdome and Netflix are working fine.
Thanks.
[kodi.log](https://github.com/JinRonin/plugin.video.eurosportplayer/files/1821972/kodi.log)

**Comment by JinRonin** [comment]
Sorry, not sure whats wrong there.
Playback is handled by inputstream adaptive (hls - not dash like the other mentioned addons) / kodi and your issue seems not to be addon related.

Its probably better to go back to the previous working kodi version you had installed and wait for a fix.

**Comment by JinRonin** [comment]
Fixed with https://github.com/peak3d/inputstream.adaptive/commit/7e86870a15ac8c50d032af66101e870db90c7140

Thanks for the report and fix :+1:

**Comment by 123chuck123** [comment]
I just wanted to do a downgrade.
Read your reply. 
Updated inputstream and Eurosport Player is working again. 
Thanks.
