### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by arashbh** [JinRonin/plugin.video.eurosportplayer#6]
Hi Jin,

I have tried setting it up on my kodi 17.6 on my Apple TV gen4 but every time I open the addon, it only asks me for my email address apparently ( prompts me only once) and then it freezes. Nothing takes place after I set my email address. I have gone through the codes and I have noticed that you have a Python script for client which does the authentication with Json. I was wondering if I can hardcode my credentials in the file so it automatically jumps in without asking me anything. If so can you tell me which part of the code I should replace with my credentials. Is it the email and password in the post_data section of the authentication function?

Much appreciated.

Arash

**Comment by JinRonin** [comment]
You can hardcode your credentials at your own risk here:
https://github.com/JinRonin/plugin.video.eurosportplayer/blob/master/resources/lib/common.py#L68

**Comment by arashbh** [comment]
Thank you for getting back to me so quick Jin. Appreciate it.
