### ISSUE TITLE
Schedule doesnt work.

### ISSUE THREAD

**Issue by mac1202** [JinRonin/plugin.video.eurosportplayer#7]
Hello when I try to open the schedule folder I got a error.
[Debug log](https://pastebin.com/kkSFSq9Y)

**Comment by JinRonin** [comment]
Thanks for the report and log.
I have uploaded a fix. Can you please test it?
https://github.com/JinRonin/plugin.video.eurosportplayer/releases/tag/v2.0.8

**Comment by mac1202** [comment]
Fixed thx. Just a little feature request could you add an option to force a different for the schedule. The one O set in addon setting is a thumbnail wall and it doesnt fit at all for the schedule. I would prefer to use a view based on a list.

**Comment by JinRonin** [comment]
will look into this, thanks.

**Comment by JinRonin** [comment]
@mac1202 
added to settings. 
Can you check please and tell me if thats ok for you?

**Comment by JinRonin** [comment]
Thats a python bug it seems. I'll add the suggested workaround from here:
https://bugs.python.org/msg221094

The first view id is for lists that include folders only. I will rename it to make it more clear

**Comment by JinRonin** [comment]
@mac1202 
Can you replace common.py in .kodi/addons/plugin.video.eurosportplayer/resources/lib
with this one and report back please? Thank you
https://www.dropbox.com/s/hxw473mchq9ujsl/common.py?dl=1

**Comment by mac1202** [comment]
Replaced the file yesterday since the error doesnt show up. That's look good to me.
