### ISSUE TITLE
Cant open stream

### ISSUE THREAD

**Issue by konuch** [JinRonin/plugin.video.eurosportplayer#8]
Hello, 

Im unable to play stream, looking at the logs, it seems like the urls pointing to stream is not correct, as it's throwing 404.
I've attached a log file below.

Thanks in advance

[kodi.log](https://github.com/JinRonin/plugin.video.eurosportplayer/files/1976446/kodi.log)

**Comment by JinRonin** [comment]
That was a bug in inputstream adaptive. Just update your libreelec build.

**Comment by konuch** [comment]
Thanks, it did the trick :)
