### ISSUE TITLE
Can't play any video Live/Replay on Raspberry Pi 3

### ISSUE THREAD

**Issue by tug912** [JinRonin/plugin.video.eurosportplayer#9]
Hi i'm using it on PC and Rapsberry Pi. Works fine on PC but doesn't work on Raspberry Pi 3.

Live or replay, nothing works. Video try to launch but it never does. I have a message like "unable to play video"

Anything to resolve this issue ?

**Comment by JinRonin** [comment]
Please provide a log file for further assistance.

http://kodi.wiki/view/Log_file/Advanced

**Comment by tug912** [comment]
Hi, here is the relevant log file part : 

17:56:18.558 T:1958400000  NOTICE: VideoPlayer: Opening: https://hlslinear-l3c.ams1.media.eurosportplayer.com/token=exp=1526831778~id=CNO-02839824~hash=4fb8e86b35d60cefc84309a77992237f3f777afc/ls01/eurosport/linear/channel/EUROSPORT_1_FRANCE-1523836370113/master_wired50_slide.m3u8
17:56:18.558 T:1958400000 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
17:56:18.559 T:935326704  NOTICE: Creating InputStream
17:56:18.559 T:935326704  NOTICE: Creating Demuxer
17:56:29.106 T:935326704   ERROR: OpenDemuxStream - Error creating demuxer
17:56:29.106 T:935326704  NOTICE: CVideoPlayer::OnExit()
17:56:29.107 T:1958400000   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.eurosportplayer/?id=https%3A%2F%2Fglobal-api.svcs.eurosportplayer.com%2Fchannels%2Fb6ee29da-a83e-4aa0-9b96-3d97585c9b18%2Fscenarios%2F%7Bscenario%7D&params=&mode=play&title=E1FR+%5BCOLOR+red%5DLIVE%5B%2FCOLOR%5D+%5BI%5DTour+de+l%27Ain+%3A+2e+%C3%A9tape%5B%2FI%5D]
17:56:29.193 T:1958400000  NOTICE: CVideoPlayer::CloseFile()
17:56:29.194 T:1958400000  NOTICE: VideoPlayer: waiting for threads to exit
17:56:29.194 T:1958400000  NOTICE: VideoPlayer: finished waiting
17:56:29.194 T:1958400000  NOTICE: CVideoPlayer::CloseFile()
17:56:29.194 T:1958400000  NOTICE: VideoPlayer: waiting for threads to exit
17:56:29.194 T:1958400000  NOTICE: VideoPlayer: finished waiting
17:56:34.800 T:1958400000  NOTICE: VideoPlayer: Opening: https://hlslinear-l3c.ams1.media.eurosportplayer.com/token=exp=1526831794~id=CNO-02839824~hash=dbe62d364901cb557bf8a35d2434c1919b0a13fb/ls01/eurosport/linear/channel/EUROSPORT_2_FRANCE-1523800849935/master_wired50_slide.m3u8
17:56:34.800 T:1958400000 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
17:56:34.800 T:935326704  NOTICE: Creating InputStream
17:56:34.801 T:935326704  NOTICE: Creating Demuxer
17:56:44.930 T:935326704   ERROR: OpenDemuxStream - Error creating demuxer
17:56:44.930 T:935326704  NOTICE: CVideoPlayer::OnExit()
17:56:44.931 T:1958400000   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.eurosportplayer/?id=https%3A%2F%2Fglobal-api.svcs.eurosportplayer.com%2Fchannels%2F2243475f-7315-4e69-8951-b834d010bc4d%2Fscenarios%2F%7Bscenario%7D&params=&mode=play&title=E2FR+%5BCOLOR+red%5DLIVE%5B%2FCOLOR%5D+%5BI%5DFormule+E+%3A+%C3%A0+Berlin%5B%2FI%5D]
17:56:44.939 T:1958400000  NOTICE: CVideoPlayer::CloseFile()
17:56:44.939 T:1958400000  NOTICE: VideoPlayer: waiting for threads to exit
17:56:44.939 T:1958400000  NOTICE: VideoPlayer: finished waiting

**Comment by tug912** [comment]
You can close the topic. I resolved it updating to last osmc version !

Thanks
